### ISSUE TITLE
Include MM1 comparison in docs

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/ASQ#7]
_From @drvinceknight on October 30, 2015 21:35_

Nice to have as a demo in your documentation a comparison between the theoretic MM1 $pi_i$ and those obtained by `qnetsim`.

_Copied from original issue: geraintpalmer/QNetSim#19_

**Comment by geraintpalmer** [comment]
_From @drvinceknight on October 30, 2015 21:38_

With plots etc..

**Comment by drvinceknight** [comment]
Is this in? If someone else wrote the issue, always nice to communicate what happened when you closed it. Took a quick look at your commit messages but `more documentation` didn't tell me much.

**Comment by geraintpalmer** [comment]
Its in: http://asq-simulates-queues.readthedocs.org/en/latest/Examples/mm1.html

**Comment by drvinceknight** [comment]
Sweet. Just going to submit a PR with some typos.
